///////////////////////////////////////////////////////////
//  Usuario.cs
//  Implementation of the Class Usuario
//  Generated by Enterprise Architect
//  Created on:      24-mai-2020 08:59:48
//  Original author: aline
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Microsoft.EntityFrameworkCore.Scaffolding.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations;
using System.Collections;

public class Usuario {
	[Key]
	public int IdUsuario { get; set; }
	private string Cpf;
	//ano, mês, dia, hora, minuto e segundo
	private DateTime DataNascimento;
	private string Email;
	private string Nome;
	private string NomeMae;
	private string Rg;
	private string Senha;
	private List<UnidadeConsumidora> UnidadesConsumidoras;
	public UnidadeConsumidora m_UnidadeConsumidora;

	public Usuario(){

	}

	~Usuario(){

	}

	/// 
	/// <param name="Usuario"></param>
	public void CadastrarUsuario(Usuario Usuario){

	}

	public Usuario ConsultarUsuario(int CPF){
		Usuario Usuario = new Usuario();
		return Usuario;
	}

	/// 
	/// <param name="Usuario"></param>
	public void EditarUsuario(Usuario Usuario){

	}

	public string getCpf(){
		return this.Cpf;
	}

	public DateTime getDataNascimento(){
		return this.DataNascimento;
	}

	public string getEmail(){
		return this.Email;
	}

	public string getNome(){
		return this.Nome;
	}

	public string getNomeMae(){
		return this.NomeMae;
	}

	public string getRg(){
		return this.Rg;
	}

	public List<UnidadeConsumidora> getUnidadesConsumidoras(){
		List<UnidadeConsumidora> UC = new List<UnidadeConsumidora>();
		return UC;
	}

	/// 
	/// <param name="Cpf"></param>
	public void setCpf(string Cpf){
		this.Cpf = Cpf;
	}

	/// 
	/// <param name="DataNascimento"></param>
	public void setDataNascimento(DateTime DataNascimento){
		this.DataNascimento = DataNascimento;
	}

	/// 
	/// <param name="Email"></param>
	public void setEmail(string Email){
		this.Email = Email;
	}

	/// 
	/// <param name="Nome"></param>
	public void setNome(string Nome){
		this.Nome = Nome;
	}

	/// 
	/// <param name="NomeMae"></param>
	public void setNomeMae(string NomeMae){
		this.NomeMae = NomeMae;
	}

	/// 
	/// <param name="Rg"></param>
	public void setRg(string Rg){
		this.Rg = Rg;
	}

	/// 
	/// <param name="Senha"></param>
	public void setSenha(string Senha){
		this.Senha = Senha;
	}

	/// 
	/// <param name="UnidadeConsumidora"></param>
	public void setUnidadesConsumidoras(UnidadeConsumidora UnidadeConsumidora){
		this.UnidadesConsumidoras = UnidadesConsumidoras;
	}

}//end Usuario