///////////////////////////////////////////////////////////
//  Fatura.cs
//  Implementation of the Class Fatura
//  Generated by Enterprise Architect
//  Created on:      24-mai-2020 09:00:26
//  Original author: aline
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Fatura {

	private string CodigoDeBarras;
	private double Consumo;
	private int Mes;
	private Boolean Pagamento;
	private int UnidadeConsumidora;
	private double Valor;

	public Fatura(){

	}

	~Fatura(){

	}

	/// 
	/// <param name="Medidor"></param>
	public int CalculoFaturaEstimada(string Medidor){

		return 0;
	}

	/// 
	/// <param name="Mes"></param>
	public Fatura ConsultaFatura(int Mes){

		return null;
	}

	public string getCodigoDeBarras(){

		return "";
	}

	public double getConsumo(){

		return 0;
	}

	public int getMes(){

		return 0;
	}

	public Boolean getPagamento(){

		return false;
	}

	public UnidadeConsumidora getUnidadeConsumidora(){

		return null;
	}

	public double getValor(){

		return 0;
	}

}//end Fatura