///////////////////////////////////////////////////////////
//  UnidadeConsumidora.cs
//  Implementation of the Class UnidadeConsumidora
//  Generated by Enterprise Architect
//  Created on:      24-mai-2020 08:59:59
//  Original author: aline
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class UnidadeConsumidora {

	private string Descricao;
	private int Endereco;
	private string NumeroUC;
	private int Usuario;
	public Endereco m_Endereco;
	public Fatura m_Fatura;

	public UnidadeConsumidora(){

	}

	~UnidadeConsumidora(){

	}

	/// 
	/// <param name="UnidadeConsumidora"></param>
	public void CadastrarUnidadeConsumidora(UnidadeConsumidora UnidadeConsumidora){

	}

	/// 
	/// <param name="Descricao"></param>
	public void EditarDescricao(string Descricao){

	}

	public string getDescricao(){

		return "";
	}

	public Endereco getEndereco(){

		return null;
	}

	public string getNumeroUC(){

		return "";
	}

	public Usuario getUsuario(){

		return null;
	}

	/// 
	/// <param name="Descricao"></param>
	public void setDescricao(string Descricao){

	}

	/// 
	/// <param name="Endereco"></param>
	public void setEndereco(Endereco Endereco){

	}

	/// 
	/// <param name="NumeroUC"></param>
	public void setNumeroUC(string NumeroUC){

	}

	/// 
	/// <param name="Usuario"></param>
	public void setUsuario(Usuario Usuario){

	}

}//end UnidadeConsumidora