///////////////////////////////////////////////////////////
//  Usuario.cs
//  Implementation of the Class Usuario
//  Generated by Enterprise Architect
//  Created on:      24-mai-2020 08:59:48
//  Original author: aline
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Usuario {

	private string Cpf;
	private DateTime DataNascimento;
	private string Email;
	private string Nome;
	private string NomeMae;
	private string Rg;
	private string Senha;
	private List<UnidadeConsumidora> UnidadesConsumidoras;
	public UnidadeConsumidora m_UnidadeConsumidora;

	public Usuario(){

	}

	~Usuario(){

	}

	/// 
	/// <param name="Usuario"></param>
	public void CadastrarUsuario(Usuario Usuario){

	}

	public Usuario ConsultarUsuario(){

		return null;
	}

	/// 
	/// <param name="Usuario"></param>
	public void EditarUsuario(Usuario Usuario){

	}

	public string getCpf(){

		return "";
	}

	public DateTime getDataNascimento(){

		return DataNascimento;
	}

	public string getEmail(){

		return "";
	}

	public string getNome(){

		return "";
	}

	public string getNomeMae(){

		return "";
	}

	public string getRg(){

		return "";
	}

	public List<UnidadeConsumidora> getUnidadesConsumidoras(){

		return null;
	}

	/// 
	/// <param name="Cpf"></param>
	public void setCpf(string Cpf){

	}

	/// 
	/// <param name="DataNascimento"></param>
	public void setDataNascimento(DateTime DataNascimento){

	}

	/// 
	/// <param name="Email"></param>
	public void setEmail(string Email){

	}

	/// 
	/// <param name="Nome"></param>
	public void setNome(string Nome){

	}

	/// 
	/// <param name="NomeMae"></param>
	public void setNomeMae(string NomeMae){

	}

	/// 
	/// <param name="Rg"></param>
	public void setRg(string Rg){

	}

	/// 
	/// <param name="Senha"></param>
	public void setSenha(string Senha){

	}

	/// 
	/// <param name="UnidadeConsumidora"></param>
	public void setUnidadesConsumidoras(UnidadeConsumidora UnidadeConsumidora){

	}

}//end Usuario